### ISSUE TITLE
o ma gad

### ISSUE THREAD

**Issue by vsem-azamat** [rybinaaaaa/courses-jdbc-dmdev#1]
This is Haram, sister.... Where is your hijab...

![image](https://github.com/rybinaaaaa/jdbc-dmdev/assets/60985938/a1ec9074-772e-4500-8355-f30abd17b2b3)

![image](https://github.com/rybinaaaaa/jdbc-dmdev/assets/60985938/5b6cdea0-8bed-41fc-a899-cbc994af8cf1)

**Comment by ArtemGubin** [comment]
I mean that's alright sista

**Comment by vsem-azamat** [comment]
@rabinart Look it this, bruh

**Comment by vsem-azamat** [comment]
> I mean that's alright sista

![image](https://github.com/rybinaaaaa/jdbc-dmdev/assets/60985938/62290fe2-32e8-4b93-8908-391f66d7860c)

**Comment by vsem-azamat** [comment]
@ArtemGubin @rabinart, Guys, issue is done #2 . Good team work!

**Comment by ArtemGubin** [comment]
Congrats
